'use strict';
const express = require('express');
const cheerio = require('cheerio');
const AdmZip  = require('adm-zip');
const https   = require('https');
const http    = require('http');
const zlib    = require('zlib');
const { URL } = require('url');
 
const app  = express();
const serverless = require('serverless-http');
 
app.use((req, res, next) => {
  res.header('Access-Control-Allow-Origin',  '*');
  res.header('Access-Control-Allow-Headers', '*');
  res.header('Access-Control-Allow-Methods', 'GET, OPTIONS');
  if (req.method === 'OPTIONS') return res.sendStatus(200);
  next();
});
 
// ================================================================
//  PROXY CONFIG  ← edit these three lines to swap proxies
// ================================================================
const PROXY_1 = 'https://corsproxy.io/?url=';
const PROXY_2 = 'https://api.codetabs.com/v1/proxy?quest=';
const PROXY_3 = 'https://thingproxy.freeboard.io/fetch/';
// ================================================================
 
const BASE         = 'https://subf2m.co';
const TMDB_KEY     = process.env.TMDB_KEY || '30166e2db6b420d3f230808cd1bb2c90';
const TMDB_BASE    = 'https://api.themoviedb.org/3';
const MAX_PER_LANG = 2;


// ================================================================
//  HARDENED SUBF2M ENGINE
// ================================================================
const CACHE_TTL       = 6 * 60 * 60 * 1000;
const NEG_CACHE_TTL   = 15 * 60 * 1000;
const REQ_TIMEOUT     = 18_000;
const DL_TIMEOUT      = 30_000;
const TMDB_TIMEOUT    = 10_000;
const MAX_DETAIL      = 60;
const MIN_DETAIL      = 12;
const MAX_REDIRECTS   = 6;
const MAX_BODY_BYTES  = 12 * 1024 * 1024;
const MAX_SRT_BYTES   = 50 * 1024 * 1024;
const CACHE_LIMIT     = 1800;
const DETAIL_CONCURRENCY = 5;
const PROBE_DELAY     = 100;
const SEARCH_DELAY    = 140;

const ALLOWED_LANGS = new Set(['english', 'arabic']);

const OTHER_LANGS = [
  'french','spanish','portuguese','german','italian','turkish','persian','farsi',
  'hindi','russian','polish','dutch','swedish','norwegian','danish','finnish',
  'korean','japanese','chinese','malay','indonesian','vietnamese','thai','greek',
  'hungarian','czech','romanian','bulgarian','hebrew','ukrainian','serbian',
  'croatian','slovak','slovenian','latvian','estonian','lithuanian','albanian',
  'azerbaijani','bosnian','catalan','georgian','icelandic','macedonian','mongolian',
  'punjabi','sinhala','tamil','bengali','urdu','nepali','khmer','burmese',
  'afrikaans','swahili',
];

const ORDINALS = [
  '', 'first', 'second', 'third', 'fourth', 'fifth', 'sixth', 'seventh',
  'eighth', 'ninth', 'tenth', 'eleventh', 'twelfth', 'thirteenth',
  'fourteenth', 'fifteenth', 'sixteenth', 'seventeenth', 'eighteenth',
  'nineteenth', 'twentieth', 'twenty-first', 'twenty-second', 'twenty-third',
  'twenty-fourth', 'twenty-fifth', 'twenty-sixth', 'twenty-seventh',
  'twenty-eighth', 'twenty-ninth', 'thirtieth',
];

const QUALITY_TERMS = [
  { bonus: 13, terms: [/\bbluray\b/i, /\bblu[- ]?ray\b/i, /\bbdrip\b/i, /\bbdremux\b/i, /\b4k\b/i, /\b2160p\b/i, /\b1080p\b/i] },
  { bonus: 10, terms: [/\bweb[- ]?dl\b/i, /\bwebrip\b/i, /\bamzn\b/i, /\bnflx\b/i, /\bhbo\b/i, /\bdsnp\b/i, /\bappletv\b/i, /\batvp\b/i, /\bpcok\b/i, /\bhulu\b/i] },
  { bonus: 5,  terms: [/\bhdtv\b/i, /\b720p\b/i, /\bhdrip\b/i, /\bweb\b/i] },
  { bonus: 8,  terms: [/\bproper\b/i, /\brepack\b/i, /\breal[. -]?proper\b/i, /\bsynced\b/i, /\bsync\b/i, /\bfixed\b/i, /\bcorrected\b/i, /\bv2\b/i, /\bv3\b/i] },
];

const AI_PATTERNS = [
  /\ba\.i\.?\b/i,
  /\bai[\s._-]?(?:sub(?:title)?s?|translat(?:ion|ed|e)?|generat(?:ed|ion|e)?|correct(?:ed|ion)?|made|creat(?:ed|ion|e)?)\b/i,
  /\b(?:translat(?:ed|ion|e)?|generat(?:ed|ion|e)?|creat(?:ed|ion|e)?|made|sub(?:title)?s?)\s+(?:by\s+)?ai\b/i,
  /\bmachine[\s._-]?translat(?:ion|ed|e)?\b/i,
  /\bauto[\s._-]?(?:translat(?:ion|ed|e)?|generat(?:ed|ion|e)?|sub(?:title)?s?)\b/i,
  /\bautosub(?:s)?\b/i,
  /\bchatgpt\b/i, /\bgpt[\s._-]?[34o]?\b/i, /\bdeep[\s._-]?l\b/i,
  /\bgoogle[\s._-]?translat(?:e|ion|ed)?\b/i,
  /\byandex[\s._-]?translat(?:e|ion|ed)?\b/i,
  /\bamazon[\s._-]?translat(?:e|ion|ed)?\b/i,
  /\bmicrosoft[\s._-]?translat(?:e|ion|ed)?\b/i,
  /\bbing[\s._-]?translat(?:e|ion|ed)?\b/i,
  /\bopenai\b/i, /\bwhisper\b/i, /\bgemini\b/i, /\bclaude\b/i,
  /\bllama\b/i, /\bneural[\s._-]?(?:translat|sub|machine)\w*\b/i,
  /\bnmt\b/i, /\bartificial[\s._-]?intelligence\b/i,
  /\bcomputer[\s._-]?(?:translat|generat)\w*\b/i,
];

const AI_QUICK_HITS = [
  'a.i', 'chatgpt', 'deepl', 'whisper', 'openai', 'gemini', 'claude', 'llama',
  'machine translat', 'auto translat', 'auto-translat', 'auto generat', 'autosub',
  'neural', 'yandex', 'bing translat', 'google translat', 'amazon translat',
  'microsoft translat', 'nmt', 'artificial intel', ' ai sub', 'ai-sub',
  'ai translat', 'translated by ai', 'generated by ai',
];

function isAISub(text) {
  if (!text) return false;
  const s = String(text);
  const lo = s.toLowerCase();
  const quick = AI_QUICK_HITS.some(x => lo.includes(x)) || /\bai\b/i.test(s);
  if (!quick) return false;
  return AI_PATTERNS.some(rx => rx.test(s));
}

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';

// ================================================================
//  CACHE
// ================================================================
const _cache = new Map();
function cacheGet(key) {
  const item = _cache.get(key);
  if (!item) return null;
  const ttl = item.negative ? NEG_CACHE_TTL : CACHE_TTL;
  if (Date.now() - item.ts > ttl) {
    _cache.delete(key);
    return null;
  }
  return item.val;
}
function cacheSet(key, val, negative = false) {
  if (_cache.size >= CACHE_LIMIT) {
    const remove = Math.max(100, Math.floor(CACHE_LIMIT * 0.12));
    let n = 0;
    for (const k of _cache.keys()) {
      _cache.delete(k);
      if (++n >= remove) break;
    }
  }
  _cache.set(key, { val, ts: Date.now(), negative: !!negative });
}
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));

// ================================================================
//  HTTP CORE
// ================================================================
function _request(urlStr, opts = {}, redirects = 0) {
  return new Promise((resolve, reject) => {
    if (!urlStr || redirects > MAX_REDIRECTS) return reject(new Error('Invalid redirect chain'));
    let parsed;
    try { parsed = new URL(urlStr); } catch (_) { return reject(new Error('Invalid URL')); }
    const lib = parsed.protocol === 'https:' ? https : http;
    const timeout = opts.timeout || REQ_TIMEOUT;
    const maxBytes = opts.maxBytes || MAX_BODY_BYTES;
    const reqOpts = {
      hostname: parsed.hostname,
      port: parsed.port || (parsed.protocol === 'https:' ? 443 : 80),
      path: parsed.pathname + parsed.search,
      method: 'GET',
      headers: {
        'User-Agent': UA,
        'Accept': opts.binary ? 'application/zip,application/octet-stream,*/*' : 'text/html,application/xhtml+xml,*/*;q=0.8',
        'Accept-Language': opts.lang === 'arabic' ? 'ar,en-US;q=0.8,en;q=0.6' : 'en-US,en;q=0.9',
        'Accept-Encoding': 'gzip, deflate, br',
        'Referer': `${BASE}/`,
        'Connection': 'keep-alive',
        'Cache-Control': 'no-cache',
        'Upgrade-Insecure-Requests': '1',
        ...(opts.headers || {}),
      },
    };
    const req = lib.request(reqOpts, res => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        const next = new URL(res.headers.location, urlStr).toString();
        res.resume();
        return _request(next, opts, redirects + 1).then(resolve).catch(reject);
      }
      if (res.statusCode === 404) { res.resume(); return resolve(null); }
      if (res.statusCode !== 200) { res.resume(); return resolve(null); }
      let total = 0;
      const chunks = [];
      let stream = res;
      const enc = String(res.headers['content-encoding'] || '').toLowerCase();
      try {
        if (enc.includes('gzip')) stream = res.pipe(zlib.createGunzip());
        else if (enc.includes('br')) stream = res.pipe(zlib.createBrotliDecompress());
        else if (enc.includes('deflate')) stream = res.pipe(zlib.createInflate());
      } catch (e) { res.resume(); return reject(e); }
      stream.on('data', c => {
        total += c.length;
        if (total > maxBytes) {
          stream.destroy(new Error('Response too large'));
          return;
        }
        chunks.push(c);
      });
      stream.on('end', () => {
        const buf = Buffer.concat(chunks);
        resolve(opts.binary ? buf : buf.toString('utf8'));
      });
      stream.on('error', reject);
    });
    req.setTimeout(timeout, () => { req.destroy(new Error('Timeout')); });
    req.on('error', reject);
    req.end();
  });
}

async function getHTML(url, tries = 3, lang = 'english') {
  for (let i = 0; i < tries; i++) {
    try {
      const r = await _request(url, { timeout: REQ_TIMEOUT, lang });
      if (r !== null) return r;
    } catch (_) {}
    if (i < tries - 1) await sleep(700 * (i + 1));
  }
  return null;
}

async function getBinary(url, tries = 3) {
  for (let i = 0; i < tries; i++) {
    try {
      const r = await _request(url, { binary: true, timeout: DL_TIMEOUT, maxBytes: MAX_SRT_BYTES });
      if (r !== null) return r;
    } catch (_) {}
  }
  const enc = encodeURIComponent(url);
  const proxied = [
    `${PROXY_1}${enc}`,
    `${PROXY_2}${enc}`,
    `${PROXY_3}${url}`,
  ];
  for (const pUrl of proxied) {
    try {
      const r = await _request(pUrl, { binary: true, timeout: DL_TIMEOUT, maxBytes: MAX_SRT_BYTES });
      if (r && r.length > 50) return r;
    } catch (_) {}
  }
  return null;
}

// ================================================================
//  STRING / TITLE NORMALIZATION
// ================================================================
function _clean(t) { return String(t || '').replace(/\s+/g, ' ').trim(); }
function normalizeTitle(t) {
  return _clean(t)
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[&+]/g, ' and ')
    .replace(/['’`]/g, '')
    .replace(/[^a-z0-9]+/g, ' ')
    .replace(/\b(the|a|an)\b/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}
function titleToSlug(title, year) {
  const base = (title || '').toLowerCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9\s]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
  return year ? `${base}-${year}` : base;
}
function normNumber(n) { return n == null || n === '' ? null : Number(n); }

// ================================================================
//  RELEASE FINGERPRINT
// ================================================================
const SOURCE_ALIASES = [
  ['web-dl', 'webdl'], ['web_dl', 'webdl'], ['web dl', 'webdl'], ['web-rip', 'webrip'],
  ['bluray', 'bluray'], ['blu-ray', 'bluray'], ['bdrip', 'bdrip'], ['bdremux', 'bdremux'],
  ['webrip', 'webrip'], ['hdtv', 'hdtv'], ['amzn', 'amzn'], ['amazon', 'amzn'],
  ['nf', 'netflix'], ['netflix', 'netflix'], ['dsnp', 'dsnp'], ['disney+', 'dsnp'],
  ['atvp', 'atvp'], ['appletv', 'atvp'], ['hbo', 'hbo'], ['hmax', 'hbo'], ['pcok', 'pcok'],
  ['hulu', 'hulu'], ['paramount', 'paramount'], ['pplus', 'paramount'],
];

function normalizeReleaseText(text) {
  return _clean(text)
    .replace(/[\[\](){},]/g, ' ')
    .replace(/[._]+/g, ' ')
    .replace(/-/g, ' - ')
    .replace(/\s+/g, ' ')
    .trim();
}

function parseRelease(text) {
  const raw = _clean(text);
  const s = normalizeReleaseText(raw);
  const lo = s.toLowerCase();
  const tokens = {
    raw,
    season: null, episode: null, episodeEnd: null,
    resolution: null, source: null, service: null, group: null,
    codec: null, audio: null, edition: null, hdr: null,
    proper: false, repack: false, corrected: false, synced: false,
  };

  let m = raw.match(/\b[Ss](\d{1,3})[ ._-]?[Ee](\d{1,4})(?:[ ._-]?[Ee](\d{1,4}))?\b/);
  if (m) {
    tokens.season = +m[1];
    tokens.episode = +m[2];
    tokens.episodeEnd = m[3] ? +m[3] : null;
  } else {
    m = raw.match(/\b(\d{1,3})\s*[xX]\s*(\d{1,4})(?:\s*[-–]\s*(\d{1,4}))?\b/);
    if (m) {
      tokens.season = +m[1];
      tokens.episode = +m[2];
      tokens.episodeEnd = m[3] ? +m[3] : null;
    }
  }

  m = raw.match(/\b(?:season\s*)?(\d{1,2})\s*[ ._-]*x\s*(\d{1,3})\b/i);
  if (!tokens.season && m) { tokens.season = +m[1]; tokens.episode = +m[2]; }

  const res = raw.match(/\b(2160p|4k|1080p|1080i|720p|576p|576i|480p|480i)\b/i);
  if (res) tokens.resolution = res[1].toLowerCase() === '4k' ? '2160p' : res[1].toLowerCase();

  for (const [needle, value] of SOURCE_ALIASES) {
    if (lo.includes(needle)) { tokens.source = value; break; }
  }
  if (lo.includes('hdr10+')) tokens.hdr = 'hdr10+';
  else if (lo.includes('dolby vision') || /\bdv\b/i.test(raw)) tokens.hdr = 'dv';
  else if (/\bhdr\b/i.test(raw)) tokens.hdr = 'hdr';

  const codecs = [
    ['x265', 'x265'], ['h265', 'x265'], ['hevc', 'x265'], ['x264', 'x264'], ['h264', 'x264'],
    ['av1', 'av1'], ['vp9', 'vp9'], ['vc-1', 'vc1'], ['mpeg-4', 'mpeg4'], ['mpeg4', 'mpeg4'],
  ];
  for (const [needle, value] of codecs) if (lo.includes(needle)) { tokens.codec = value; break; }

  const audios = [
    ['atmos', 'atmos'], ['truehd', 'truehd'], ['dts-hd ma', 'dtshdma'], ['dts-hd', 'dtshd'],
    ['dts:x', 'dtsx'], ['dts', 'dts'], ['ddp', 'ddp'], ['dd+', 'ddp'], ['eac3', 'ddp'],
    ['ac3', 'ac3'], ['aac', 'aac'], ['flac', 'flac'],
  ];
  for (const [needle, value] of audios) if (lo.includes(needle)) { tokens.audio = value; break; }

  const editions = ['extended', 'unrated', 'director', 'directors cut', 'theatrical', 'imax', 'open matte', 'remastered', 'special edition', 'criterion'];
  for (const ed of editions) if (lo.includes(ed)) { tokens.edition = ed; break; }

  tokens.proper = /\b(?:proper|real[ ._-]?proper)\b/i.test(raw);
  tokens.repack = /\brepack\b/i.test(raw);
  tokens.corrected = /\b(?:fixed|corrected|v2|v3)\b/i.test(raw);
  tokens.synced = /\b(?:synced|sync)\b/i.test(raw);

  // Release groups are normally after a final hyphen, but never assume that blindly.
  const gm = raw.match(/(?:^|[ ._-])(?:-[ ]?)([A-Za-z][A-Za-z0-9]{1,30})\s*$/);
  if (gm) {
    const candidate = gm[1].toUpperCase();
    if (!/^(WEB|DL|RIP|REMUX|BLURAY|HDTV|X264|X265|HEVC|1080P|720P|2160P|AAC|DDP|DTS)$/.test(candidate)) {
      tokens.group = candidate;
    }
  }
  if (!tokens.group) {
    const gm2 = raw.match(/\b(?:WEB-DL|WEBRip|BluRay|HDTV|AMZN|NF|DSNP|ATVP)[ ._-]+(?:[A-Za-z0-9]+[ ._-]+){0,4}([A-Z][A-Za-z0-9]{1,20})$/);
    if (gm2 && !/^(1080p|720p|x264|x265|hevc)$/i.test(gm2[1])) tokens.group = gm2[1].toUpperCase();
  }
  return tokens;
}

function releaseKey(t) {
  if (!t) return '';
  return [t.season, t.episode, t.resolution, t.source, t.service, t.group, t.codec, t.audio, t.edition, t.hdr].join('|');
}

function qualityBonus(text) {
  if (!text) return 0;
  let bonus = 0;
  for (const tier of QUALITY_TERMS) if (tier.terms.some(rx => rx.test(text))) bonus += tier.bonus;
  return Math.min(bonus, 24);
}

function scoreReleaseMatch(sub, streamTokens, type) {
  const subText = sub.releaseInfo || sub._rawText || '';
  const st = parseRelease(subText);
  let score = 0;
  let reasons = [];
  if (streamTokens) {
    if (type === 'series') {
      if (streamTokens.season != null && streamTokens.episode != null) {
        if (st.season === streamTokens.season && st.episode === streamTokens.episode) { score += 140; reasons.push('exact episode'); }
        else if (st.season === streamTokens.season && st.episode == null) { score += 35; reasons.push('season'); }
        else if (st.season != null || st.episode != null) score -= 70;
      }
    }
    if (streamTokens.source && st.source) {
      if (streamTokens.source === st.source) { score += 28; reasons.push('source'); }
      else score -= 8;
    }
    if (streamTokens.resolution && st.resolution) {
      if (streamTokens.resolution === st.resolution) { score += 14; reasons.push('resolution'); }
      else score -= 4;
    }
    if (streamTokens.group && st.group) {
      if (streamTokens.group.toUpperCase() === st.group.toUpperCase()) { score += 38; reasons.push('group'); }
      else score -= 6;
    }
    for (const k of ['codec','audio','edition','hdr']) {
      if (streamTokens[k] && st[k]) score += streamTokens[k] === st[k] ? 8 : -2;
    }
  }
  if (sub.isGood) { score += 10; reasons.push('good'); }
  if (sub.goodVotes >= 3 && sub.goodVotes > sub.badVotes) score += Math.min(10, sub.goodVotes);
  if (sub.downloads > 0) score += Math.min(8, Math.log10(sub.downloads + 1) * 3);
  score += qualityBonus(subText);
  if (st.proper || st.repack || st.corrected || st.synced) score += 4;
  return { score, tokens: st, reasons };
}

// ================================================================
//  TMDB
// ================================================================
async function getTMDB(imdbId) {
  const ck = `tmdb:${imdbId}`;
  const hit = cacheGet(ck);
  if (hit !== null) return hit;
  try {
    const raw = await _request(`${TMDB_BASE}/find/${encodeURIComponent(imdbId)}?external_source=imdb_id&api_key=${encodeURIComponent(TMDB_KEY)}`, { timeout: TMDB_TIMEOUT });
    if (!raw) { cacheSet(ck, null, true); return null; }
    const d = JSON.parse(raw);
    let info = null;
    if (d.movie_results?.length) {
      const m = d.movie_results[0];
      info = { title: m.title || m.original_title, originalTitle: m.original_title || m.title, year: m.release_date?.slice(0,4) || null, type: 'movie', tmdbId: m.id, runtime: m.runtime || null };
    } else if (d.tv_results?.length) {
      const t = d.tv_results[0];
      info = { title: t.name || t.original_name, originalTitle: t.original_name || t.name, year: t.first_air_date?.slice(0,4) || null, type: 'series', tmdbId: t.id, runtime: null };
    }
    cacheSet(ck, info, !info);
    return info;
  } catch (_) { cacheSet(ck, null, true); return null; }
}

async function getTMDBSeasonMeta(tmdbId, season) {
  if (!tmdbId || season == null) return null;
  const ck = `tmdbseason:${tmdbId}:${season}`;
  const hit = cacheGet(ck);
  if (hit !== null) return hit;
  try {
    const raw = await _request(`${TMDB_BASE}/tv/${tmdbId}/season/${season}?api_key=${encodeURIComponent(TMDB_KEY)}`, { timeout: TMDB_TIMEOUT });
    if (!raw) { cacheSet(ck, null, true); return null; }
    const d = JSON.parse(raw);
    const meta = {
      year: d.air_date?.slice(0,4) || null,
      name: d.name || null,
      episodeCount: Array.isArray(d.episodes) ? d.episodes.length : null,
    };
    cacheSet(ck, meta, !meta.year && !meta.name);
    return meta;
  } catch (_) { cacheSet(ck, null, true); return null; }
}

// ================================================================
//  SEARCH / SLUG RESOLUTION
// ================================================================
function slugFromHref(href) {
  if (!href || !href.startsWith('/subtitles/')) return null;
  const parts = href.split('/').filter(Boolean);
  return parts.length >= 2 && parts[1] !== 'searchbytitle' ? parts[1] : null;
}

function titleSimilarity(a, b) {
  const x = normalizeTitle(a), y = normalizeTitle(b);
  if (!x || !y) return 0;
  if (x === y) return 1;
  if (x.includes(y) || y.includes(x)) return 0.88;
  const A = new Set(x.split(' ')), B = new Set(y.split(' '));
  const inter = [...A].filter(v => B.has(v)).length;
  return inter / Math.max(A.size, B.size);
}

async function _probeSlug(slug, opts = {}) {
  if (!slug || slug.length > 240) return false;
  try {
    const lang = opts.lang || 'english';
    const html = await getHTML(`${BASE}/subtitles/${slug}/${lang}`, 2, lang);
    if (!html || html.length < 400) return false;
    const $ = cheerio.load(html);
    const hasItems = $('li.item, .item, .subtitle-item, a[href*="/download"], a[href*="/english/"], a[href*="/arabic/"]').length > 0;
    if (!hasItems && !/subtitle|download/i.test(html)) return false;
    if (opts.season != null) {
      const s = Number(opts.season), pad = String(s).padStart(2,'0'), ord = (ORDINALS[s] || '').toLowerCase();
      const low = html.toLowerCase();
      return hasItems && (
        low.includes(`s${pad}e`) || low.includes(`season ${s}`) || (ord && low.includes(`${ord} season`)) ||
        low.includes(`-s${pad}`) || low.includes(`-${ord}-season`) || low.includes('class="r"') || low.includes('class="item"')
      );
    }
    return hasItems;
  } catch (_) { return false; }
}

async function _searchSeriesSlugByQuery(query, season, titleHint, seasonYear, showYear) {
  const html = await getHTML(`${BASE}/subtitles/searchbytitle?query=${encodeURIComponent(query)}&l=`);
  if (!html) return null;
  const $ = cheerio.load(html);
  const ord = (ORDINALS[season] || '').toLowerCase();
  const expectedTitle = titleHint || query;
  const results = [];
  const seen = new Set();
  $('a[href^="/subtitles/"]').each((_, a) => {
    const href = $(a).attr('href') || '';
    const slug = slugFromHref(href);
    if (!slug || seen.has(slug)) return;
    seen.add(slug);
    const text = _clean($(a).text());
    const low = text.toLowerCase();
    let score = titleSimilarity(text.replace(/\s*\(\d{4}\).*$/, '').replace(/\s*[-–].*$/, ''), expectedTitle) * 100;
    const m = text.match(/\((\d{4})\)/);
    const year = m ? m[1] : null;
    const seriesMatch = text.match(/^(.+?)\s*[-–]\s*(.*?)\s*(?:season|series)\s*(?:\((\d{4})\))?\s*$/i);
    if (seriesMatch) {
      const subOrd = _clean(seriesMatch[2]).toLowerCase();
      if (ord && subOrd === ord) score += 240;
      else if (subOrd === String(season)) score += 180;
      else if (ord && subOrd.startsWith(ord)) score += 170;
      if (seasonYear && seriesMatch[3] === seasonYear) score += 70;
      else if (showYear && year === showYear && season === 1) score += 35;
    }
    const sl = slug.toLowerCase();
    if (ord && sl.includes(`-${ord}-season`)) score += 90;
    if (sl.includes(`-season-${season}-`) || sl.includes(`-s${String(season).padStart(2,'0')}`)) score += 80;
    if (seasonYear && sl.includes(`-${seasonYear}`)) score += 35;
    if (/\bmovie\b/i.test(text)) score -= 100;
    results.push({ slug, score });
  });
  results.sort((a,b) => b.score - a.score);
  for (const r of results.slice(0, 12)) {
    await sleep(PROBE_DELAY);
    if (await _probeSlug(r.slug, { season })) return r.slug;
  }
  return null;
}

async function _smartPatternSlugs(title, season, seasonYear, showYear) {
  const base = titleToSlug(title);
  const ord = ORDINALS[season] || '';
  const pad = String(season).padStart(2,'0');
  const patterns = [];
  const years = [...new Set([seasonYear, showYear, seasonYear ? String(+seasonYear-1) : null, seasonYear ? String(+seasonYear+1) : null].filter(Boolean))];
  for (const yr of years) {
    if (ord) {
      patterns.push(`${base}-${ord}-season-${yr}`, `${base}--${ord}-season-${yr}`, `${base}-the-${ord}-season-${yr}`, `${base}-${ord}-season-tv-${yr}`);
    }
    patterns.push(`${base}-season-${season}-${yr}`, `${base}-s${pad}-${yr}`, `${base}-${yr}`);
  }
  if (ord) patterns.push(`${base}-${ord}-season`, `${base}--${ord}-season`, `${base}-the-${ord}-season`, `${base}-${ord}-series`);
  patterns.push(`${base}-season-${season}`, `${base}-s${pad}`);
  for (const slug of [...new Set(patterns)]) {
    await sleep(PROBE_DELAY);
    if (await _probeSlug(slug, { season })) return slug;
  }
  return null;
}

async function resolveSeriesSlug(imdbId, season) {
  const ck = `sslug3:${imdbId}:${season}`;
  const hit = cacheGet(ck);
  if (hit !== null) return hit;
  const tmdb = await getTMDB(imdbId);
  const title = tmdb?.title;
  const showYear = tmdb?.year;
  const seasonMeta = tmdb?.tmdbId ? await getTMDBSeasonMeta(tmdb.tmdbId, season) : null;
  const seasonYear = seasonMeta?.year || null;

  let slug = await _searchSeriesSlugByQuery(imdbId, season, title, seasonYear, showYear);
  if (slug) { cacheSet(ck, slug); return slug; }
  if (title) {
    slug = await _searchSeriesSlugByQuery(title, season, title, seasonYear, showYear);
    if (slug) { cacheSet(ck, slug); return slug; }
  }
  if (title) {
    slug = await _smartPatternSlugs(title, season, seasonYear, showYear);
    if (slug) { cacheSet(ck, slug); return slug; }
    const bare = titleToSlug(title);
    if (await _probeSlug(bare, { season })) { cacheSet(ck, bare); return bare; }
    if (showYear && await _probeSlug(titleToSlug(title, showYear), { season })) { const s = titleToSlug(title, showYear); cacheSet(ck, s); return s; }
  }
  cacheSet(ck, null, true);
  return null;
}

async function _searchMovieSlugs(query, yearHint) {
  const html = await getHTML(`${BASE}/subtitles/searchbytitle?query=${encodeURIComponent(query)}&l=`);
  if (!html) return [];
  const $ = cheerio.load(html);
  const results = [];
  const seen = new Set();
  $('a[href^="/subtitles/"]').each((_, a) => {
    const href = $(a).attr('href') || '';
    const slug = slugFromHref(href);
    if (!slug || seen.has(slug)) return;
    seen.add(slug);
    const text = _clean($(a).text());
    const m = text.match(/\((\d{4})\)/);
    const year = m ? +m[1] : null;
    let score = titleSimilarity(text.replace(/\s*\(\d{4}\)\s*$/, ''), query) * 100;
    if (query.startsWith('tt')) score += 110;
    if (yearHint && year === +yearHint) score += 45;
    if (/\bseason\b|\bseries\b/i.test(text)) score -= 50;
    results.push({ slug, text, score });
  });
  return results.sort((a,b) => b.score-a.score);
}

async function _probeMovieSlug(slug, expectedTitle) {
  if (!slug) return false;
  try {
    const html = await getHTML(`${BASE}/subtitles/${slug}/english`, 2, 'english');
    if (!html || html.length < 500) return false;
    const $ = cheerio.load(html);
    const pageTitle = _clean($('title').text());
    const hasItems = $('li.item, .item, .subtitle-item').length > 0 || /download|subtitle/i.test(html);
    if (!hasItems) return false;
    return !expectedTitle || titleSimilarity(pageTitle, expectedTitle) >= 0.45 || hasItems;
  } catch (_) { return false; }
}

async function resolveMovieSlug(imdbId, titleHint, yearHint) {
  const ck = `mslug3:${imdbId}`;
  const hit = cacheGet(ck);
  if (hit !== null) return hit;
  const tmdb = await getTMDB(imdbId);
  const title = tmdb?.title || titleHint;
  const year = tmdb?.year || yearHint;

  if (title && year) {
    const direct = titleToSlug(title, year);
    if (await _probeMovieSlug(direct, title)) { cacheSet(ck, direct); return direct; }
  }
  const queries = [...new Set([imdbId, title].filter(Boolean))];
  for (const q of queries) {
    const candidates = await _searchMovieSlugs(q, year);
    for (const c of candidates.slice(0, 10)) {
      await sleep(SEARCH_DELAY);
      if (await _probeMovieSlug(c.slug, title)) { cacheSet(ck, c.slug); return c.slug; }
    }
  }
  if (title) {
    const candidates = [];
    if (year) candidates.push(titleToSlug(title, year), titleToSlug(title, +year-1), titleToSlug(title, +year+1));
    candidates.push(titleToSlug(title));
    for (const c of [...new Set(candidates)]) {
      await sleep(PROBE_DELAY);
      if (await _probeMovieSlug(c, title)) { cacheSet(ck, c); return c; }
    }
  }
  cacheSet(ck, null, true);
  return null;
}

// ================================================================
//  SUBTITLE SCRAPING
// ================================================================
function extractSubtitleId(href) {
  if (!href) return null;
  const m = String(href).match(/\/(\d+)\/?$/);
  return m ? m[1] : null;
}
function normalizeDetailUrl(href, lang) {
  if (!href || !href.includes(`/${lang}/`)) return null;
  const id = extractSubtitleId(href);
  if (!id) return null;
  return href.startsWith('http') ? href : `${BASE}${href}`;
}

function _extractItem($, el, lang, out) {
  const $el = $(el);
  const rawText = _clean($el.text());
  let detailHref = null;
  $el.find('a[href]').each((_, a) => {
    const h = $(a).attr('href') || '';
    if (!detailHref && h.includes(`/${lang}/`)) detailHref = normalizeDetailUrl(h, lang);
  });
  if (!detailHref) return;
  const hLow = detailHref.toLowerCase();
  if (OTHER_LANGS.some(ol => hLow.includes(`/${ol}/`))) return;
  const subId = extractSubtitleId(detailHref);
  if (!subId) return;
  const isGood = (
    $el.find('.green-icon, .positive-icon').length > 0 ||
    $el.find('img[alt="good"], img[alt="Positive"], img[alt="positive"]').length > 0 ||
    $el.hasClass('good') || $el.hasClass('positive') || /\bgood\b/i.test($el.attr('class') || '')
  );
  const comment = _clean($el.find('p.comment, .comment').first().text());
  const releaseLines = $el.find('.r li, ul.release li, ul.scrolllist li, ul li').map((_, li) => _clean($(li).text())).get().filter(Boolean);
  const releaseInfo = (releaseLines.join(' | ') || rawText).substring(0, 240);
  if (isAISub(`${comment} ${releaseInfo}`)) return;
  out.push({ subId, detailUrl: detailHref, isGood, releaseInfo, comment, authorNote: '', lang, goodVotes: 0, badVotes: 0, downloads: 0, _rawText: rawText });
}

async function mapLimit(items, limit, fn) {
  const out = new Array(items.length);
  let next = 0;
  async function worker() {
    while (true) {
      const i = next++;
      if (i >= items.length) return;
      try { out[i] = await fn(items[i], i); } catch (_) { out[i] = null; }
    }
  }
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, worker));
  return out;
}

async function _enrichSub(sub) {
  const ck = `det3:${sub.subId}`;
  const hit = cacheGet(ck);
  if (hit !== null) return hit.__aiBlocked ? null : { ...sub, ...hit };
  const html = await getHTML(sub.detailUrl, 2, sub.lang);
  if (!html) { cacheSet(ck, sub); return sub; }
  const $ = cheerio.load(html);
  const txt = $.root().text();
  const goodVotes = +(txt.match(/voted\s+as\s+good\s+by[:\s]*(\d+)/i)?.[1] ?? 0);
  const badVotes = +(txt.match(/voted\s+as\s+bad\s+by[:\s]*(\d+)/i)?.[1] ?? 0);
  const downloads = +(txt.match(/downloads?[:\s]*(\d[\d,]*)/i)?.[1]?.replace(/,/g,'') ?? 0);
  const ratio = goodVotes + badVotes >= 3 ? goodVotes / (goodVotes + badVotes) : null;
  const authorNote = _clean($('p.comment, .comment, .notes, .author-comment').first().text());
  const relLines = $('ul.release li, .release-names li, ul.scrolllist li, .release li').map((_, e) => _clean($(e).text())).get().filter(Boolean);
  const releaseInfo = (relLines.length ? relLines.join(' | ') : sub.releaseInfo).substring(0, 300);
  if (isAISub(`${authorNote} ${releaseInfo} ${sub.comment}`)) {
    cacheSet(ck, { __aiBlocked: true }, true);
    return null;
  }
  const enriched = { ...sub, releaseInfo, goodVotes, badVotes, downloads, isGood: sub.isGood || (ratio !== null && ratio >= 0.70 && goodVotes >= 2), authorNote };
  cacheSet(ck, enriched);
  return enriched;
}

async function getSubsList(slug, lang, season, episode) {
  if (!ALLOWED_LANGS.has(lang)) return [];
  // IMPORTANT: season is part of the cache key. The old implementation could collide S01E03 with S02E03.
  const ck = `list3:${slug}:${lang}:${season ?? 0}:${episode ?? 0}`;
  const hit = cacheGet(ck);
  if (hit !== null) return hit;
  const html = await getHTML(`${BASE}/subtitles/${slug}/${lang}`, 3, lang);
  if (!html) { cacheSet(ck, [], true); return []; }
  const $ = cheerio.load(html);
  const raw = [];
  $('li.item').each((_, el) => _extractItem($, el, lang, raw));
  if (!raw.length) $('tr, .subtitle-item, .item').each((_, el) => _extractItem($, el, lang, raw));
  if (!raw.length) {
    $('a[href]').each((_, a) => {
      const href = $(a).attr('href') || '';
      if (!href.includes(`/${lang}/`)) return;
      const detailUrl = normalizeDetailUrl(href, lang);
      if (!detailUrl) return;
      const subId = extractSubtitleId(detailUrl);
      if (!subId) return;
      raw.push({ subId, detailUrl, isGood:false, releaseInfo:'', comment:'', authorNote:'', lang, goodVotes:0, badVotes:0, downloads:0, _rawText:_clean($(a).text()) });
    });
  }

  const unique = [];
  const seen = new Set();
  for (const s of raw) if (!seen.has(s.subId)) { seen.add(s.subId); unique.push(s); }

  // Filter exact episode when the site gives us a recognizable episode token. If nothing matches,
  // retain the full candidate pool instead of returning an empty result.
  let candidates = unique;
  if (season != null && episode != null) {
    const exact = unique.filter(s => {
      const p = parseRelease(`${s._rawText} ${s.releaseInfo}`);
      return p.season === Number(season) && p.episode === Number(episode);
    });
    if (exact.length) candidates = exact;
  }

  // Do not throw away candidates before AI filtering. Enrich in batches and keep going until
  // enough human candidates are found or the hard limit is reached.
  const enriched = [];
  for (let i = 0; i < candidates.length && enriched.length < MAX_DETAIL; i += DETAIL_CONCURRENCY) {
    const batch = candidates.slice(i, i + DETAIL_CONCURRENCY);
    const got = await mapLimit(batch, DETAIL_CONCURRENCY, _enrichSub);
    for (const s of got) if (s && !isAISub(`${s.releaseInfo} ${s.comment} ${s.authorNote}`)) enriched.push(s);
    if (i + DETAIL_CONCURRENCY >= MIN_DETAIL && enriched.length >= Math.min(MAX_PER_LANG * 3, 6)) break;
  }
  cacheSet(ck, enriched);
  return enriched;
}

// ================================================================
//  SUBTITLE FILE VALIDATION / DECODING
// ================================================================
function _ext(n) { return n.match(/(\.[^.]+)$/)?.[1]?.toLowerCase() ?? ''; }
function _looksLikeSub(t) {
  return typeof t === 'string' && t.length > 40 && /(?:^|\n)\s*(?:\d+\s*\n)?\s*\d{1,2}:\d{2}:\d{2}[,.]\d{3}\s*-->\s*\d{1,2}:\d{2}:\d{2}[,.]\d{3}/m.test(t);
}
function _looksArabic(t) {
  return /[\u0600-\u06FF]/.test(t);
}
function decodeSubtitle(buf) {
  if (!Buffer.isBuffer(buf)) return null;
  let offset = 0;
  if (buf[0] === 0xEF && buf[1] === 0xBB && buf[2] === 0xBF) offset = 3;
  const u8 = buf.slice(offset);
  const utf8 = u8.toString('utf8');
  if (_looksLikeSub(utf8) && !utf8.includes('\uFFFD')) return utf8;
  if (typeof TextDecoder === 'function') {
    const encodings = ['utf-8', 'utf-16le', 'windows-1256', 'windows-1252', 'iso-8859-1'];
    for (const enc of encodings) {
      try {
        const t = new TextDecoder(enc, { fatal: false }).decode(u8);
        if (_looksLikeSub(t) && !t.includes('\uFFFD')) return t;
      } catch (_) {}
    }
  }
  const latin = u8.toString('latin1');
  return _looksLikeSub(latin) ? latin : null;
}
function validateSubtitleText(text) {
  if (!_looksLikeSub(text)) return { ok:false, reason:'not-subtitle' };
  const cues = text.match(/-->?/g)?.length || 0;
  if (cues < 1) return { ok:false, reason:'no-cues' };
  const bad = (text.match(/\uFFFD/g) || []).length;
  if (bad > 5) return { ok:false, reason:'encoding' };
  return { ok:true, cues, arabic:_looksArabic(text) };
}

function _extractFromZip(buf) {
  try {
    const zip = new AdmZip(buf);
    const rank = { '.srt':0, '.vtt':1, '.ass':2, '.ssa':3 };
    const files = zip.getEntries().filter(e => {
      const n = e.entryName.toLowerCase();
      return !e.isDirectory && !n.startsWith('__macosx') && Object.keys(rank).some(x => n.endsWith(x));
    }).sort((a,b) => (rank[_ext(a.entryName)] ?? 9) - (rank[_ext(b.entryName)] ?? 9));
    let fallback = null;
    for (const f of files) {
      const raw = zip.readFile(f);
      if (!raw) continue;
      const text = decodeSubtitle(raw);
      if (!text) continue;
      if (!fallback) fallback = text;
      const v = validateSubtitleText(text);
      if (v.ok) return text;
    }
    return fallback;
  } catch (_) { return null; }
}
function _tryDirect(buf) { const t = decodeSubtitle(buf); return t && validateSubtitleText(t).ok ? t : null; }

async function fetchSRT(downloadUrl) {
  const ck = `srt3:${downloadUrl}`;
  const hit = cacheGet(ck);
  if (hit !== null) return hit;
  try {
    const buf = await getBinary(downloadUrl);
    if (!buf) return null;
    const content = _extractFromZip(buf) ?? _tryDirect(buf);
    if (!content) return null;
    cacheSet(ck, content);
    return content;
  } catch (_) { return null; }
}

// ================================================================
//  SORTING / SCORING
// ================================================================
function sortForBest(subs, streamTokens, type) {
  return subs.map(s => {
    const match = scoreReleaseMatch(s, streamTokens, type);
    const languageBonus = s.lang === 'arabic' || s.lang === 'english' ? 2 : 0;
    return { ...s, _score: match.score + languageBonus, _match: match };
  }).sort((a,b) => {
    if (b._score !== a._score) return b._score - a._score;
    if (b.isGood !== a.isGood) return b.isGood ? 1 : -1;
    if (b.goodVotes !== a.goodVotes) return b.goodVotes - a.goodVotes;
    return b.downloads - a.downloads;
  });
}

function buildSubtitleName(s, flag) {
  const bits = [flag];
  if (s.isGood) bits.push('★');
  if (s.goodVotes > 0) bits.push(`[+${s.goodVotes}]`);
  if (s.downloads > 0) bits.push(`[↓${s.downloads}]`);
  if (s.releaseInfo) bits.push(s.releaseInfo);
  return _clean(bits.join(' ')).substring(0, 140);
}

// ================================================================
//  MANIFEST
// ================================================================
app.get('/manifest.json', (req, res) => {
  res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate');
  res.json({
    id: 'org.van.vansubf2mplus.steel',
    name: 'VanSubF2M Steel',
    description: 'Hardened Subf2m English & Arabic subtitles with release-aware matching and anti-AI filtering.',
    version: '3.0.0',
    resources: ['subtitles'],
    types: ['movie', 'series'],
    idPrefixes: ['tt'],
    catalogs: [],
  });
});

// ================================================================
//  SUBTITLE FILE ROUTE
// ================================================================
app.get('/sub/:enc.srt', async (req, res) => {
  let dlUrl = '';
  try { dlUrl = Buffer.from(req.params.enc, 'base64url').toString('utf8'); }
  catch (_) { return res.status(400).end('Bad request'); }
  if (!/^https:\/\/subf2m\.co\/subtitles\/[^\s]+\/download(?:\?.*)?$/i.test(dlUrl)) return res.status(403).end('Forbidden');
  const content = await fetchSRT(dlUrl);
  if (!content) return res.status(404).end('Not found');
  res.setHeader('Content-Type', 'text/plain; charset=utf-8');
  res.setHeader('Cache-Control', 'public, max-age=86400');
  res.setHeader('Content-Disposition', 'inline; filename="subtitle.srt"');
  res.end(content);
});

// ================================================================
//  MAIN STREMIO ROUTE
// ================================================================
app.get('/subtitles/:type/:id/:extra?.json', async (req, res) => {
  res.setHeader('Content-Type', 'application/json; charset=utf-8');
  const type = String(req.params.type || '').toLowerCase();
  const id = String(req.params.id || '');
  if (!['movie','series'].includes(type) || !/^tt\d+(?::\d+(?::\d+)?)?$/.test(id)) return res.json({ subtitles: [] });

  let imdbId = id, season = null, episode = null;
  if (id.includes(':')) {
    const p = id.split(':');
    imdbId = p[0];
    season = normNumber(p[1]);
    episode = normNumber(p[2]);
  }
  if (!/^tt\d+$/.test(imdbId)) return res.json({ subtitles: [] });

  const filename = String(req.query.filename || req.query.videoFilename || req.query.file || '');
  const streamTokens = parseRelease(filename);
  // Filename is authoritative for episode when it contains one, but never overwrite a valid
  // Stremio route episode with a missing filename token.
  if (type === 'series' && streamTokens.season != null && streamTokens.episode != null) {
    season = season ?? streamTokens.season;
    episode = episode ?? streamTokens.episode;
  }

  const resultKey = `result3:${type}:${imdbId}:${season ?? 0}:${episode ?? 0}:${releaseKey(streamTokens)}`;
  const cached = cacheGet(resultKey);
  if (cached !== null) return res.json({ subtitles: cached });

  try {
    let slug = null;
    let tmdb = null;
    if (type === 'series' && season != null) {
      slug = await resolveSeriesSlug(imdbId, season);
    } else {
      tmdb = await getTMDB(imdbId);
      slug = await resolveMovieSlug(imdbId, tmdb?.title || null, tmdb?.year || null);
    }
    if (!slug) {
      cacheSet(resultKey, [], true);
      return res.json({ subtitles: [] });
    }

    const [engRes, araRes] = await Promise.allSettled([
      getSubsList(slug, 'english', season, episode),
      getSubsList(slug, 'arabic', season, episode),
    ]);
    let engSubs = engRes.status === 'fulfilled' ? engRes.value : [];
    let araSubs = araRes.status === 'fulfilled' ? araRes.value : [];

    engSubs = sortForBest(engSubs, streamTokens, type).slice(0, MAX_PER_LANG);
    araSubs = sortForBest(araSubs, streamTokens, type).slice(0, MAX_PER_LANG);

    const proto = req.headers['x-forwarded-proto'] || (req.socket?.encrypted ? 'https' : 'http');
    const host = req.headers['x-forwarded-host'] || req.headers.host;
    if (!host) return res.json({ subtitles: [] });
    const origin = `${proto}://${host}`;

    const build = (subs, langCode, flag) => subs.map(s => {
      const dlUrl = `${s.detailUrl}/download`;
      const enc = Buffer.from(dlUrl).toString('base64url');
      return {
        id: `vsub-${langCode}-${s.subId}`,
        url: `${origin}/sub/${enc}.srt`,
        lang: langCode,
        name: buildSubtitleName(s, flag),
      };
    });

    const subtitles = [...build(engSubs, 'eng', 'English'), ...build(araSubs, 'ara', 'Arabic')];
    cacheSet(resultKey, subtitles, subtitles.length === 0);
    return res.json({ subtitles });
  } catch (e) {
    console.error('[route]', e?.message || e);
    cacheSet(resultKey, [], true);
    return res.json({ subtitles: [] });
  }
});

// ================================================================
//  HEALTH / DEBUG-SAFE STATUS
// ================================================================
app.get('/health', (req, res) => {
  res.json({ ok: true, service: 'VanSubF2M Steel', version: '3.0.0' });
});

module.exports.handler = serverless(app);
});
